### ISSUE TITLE
[Bug]: [Outlook] Can't pop out the message to a new window

### ISSUE THREAD

**Issue by MurzNN** [ferdium/ferdium-recipes#11]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Ferdium Version

6.0.0-nightly.20

### Recipe Name

Outlook

### Recipe Version

1.6.0

### Steps to reproduce

1. Click on a "New message" button
2. Click on the "Open in new window" button in top right corner of composer area.

### Expected Behavior

A new window should open

### Actual Behavior

The new window is not opening, the composer interface just silently disappears.

In Rambox app this works normally and shows the new separate windows with message composer.

I guess this is because of some popup blocker settings, so can we allow such popups in this recipe?

**Comment by MurzNN** [comment]
As I understand, somewhere in this file https://github.com/ferdium/ferdium-recipes/blob/34bac4b4ff262a02e668c34ecd9e6cb2eeb25935/recipes/office365-owa/package.json should be the "allowPopups" option, but can't find anything about it in docs.

**Comment by vraravam** [comment]
"New window" is not a functionality supported in Ferdium atm. Also, that would be something that the base product/app (Ferdium) needs to support, as opposed to the service recipe.
