### ISSUE TITLE
[Bug]: Telegram: Empty spaces on a large screen

### ISSUE THREAD

**Issue by danisztls** [ferdium/ferdium-recipes#13]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Ferdium Version

6.00

### Recipe Name

Telegram

### Recipe Version

Latest?

### Steps to reproduce

Open service.

### Expected Behavior

Full width.

### Actual Behavior

Empty spaces.

### Additional Information

Workround (`user.css`):

```css
#page-chats {
  max-width: 100vw !important;
}
```

**Comment by vraravam** [comment]
@danisztls - it would be good to see before and after screenshots when applying your workaround. When I tried in my Ferdium, I wasn't able to notice any difference in telegram

**Comment by danisztls** [comment]
@vraravam 

### Before
![Screenshot from 2022-05-06 01-18-39](https://user-images.githubusercontent.com/13279154/167066833-3d057f40-4133-44be-bc33-9871edfad10c.png)

### After
![Screenshot from 2022-05-06 01-19-02](https://user-images.githubusercontent.com/13279154/167066850-8e2cd0c9-b7ce-4c84-b978-7dc7467326ac.png)

**Comment by mydarkstar** [comment]
Hi @danisztls! I wanted to chime in and let you know that this in fact isn't a bug, but the intended look of the Telegram Web 'K' version.
You may want to try the 'Z' version, which does not apply this width limitation, among other differences.
Context: These two implementations are independently developed at Telegram and currently 'competing' each other.

Nonetheless, I agree that for our purposes, it would be best to apply this custom style.
I find it looks a lot better in Ferdium and I can verify your workaround to work!

If you don't mind, please open a Pull Request with your styles added to the recipe styles:
https://github.com/ferdium/ferdium-recipes/blob/main/recipes/telegram/service.css

Additionally, I wanted to point out that currently, we link `https://web.telegram.org` in the recipe.
This URL redirects you randomly to either the 'K' or 'Z' version, which means our users may get very different experiences, depending on the version they were redirected to.
Also, the styles and scripts may only work well for one version.
You can easily switch versions via the menu, but we may want to set something specific here.

**Comment by danisztls** [comment]
@mydarkstar Thanks. The 'Z' version doesn't have this issue and isn't affected by the workaround as it doesn't seem to have an element with `page-chats` class.
