### ISSUE TITLE
[Recipe Request]: Padlet Integration

### ISSUE THREAD

**Issue by bfsinger** [ferdium/ferdium-recipes#142]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Name of the service

Padlet

### URL of the service

https://padlet.com/

### GitHub URL to a recipe that has already been created by someone else or you

https://github.com/bfsinger/ferdiumpadlet

### Features you want implemented

Hi all,

I'm trying to create a Padlet service for Ferdium. Padlet is a cool app that is very flexible, allowing the user to create 'boards' where anyone can post information to. Ideally, I'd like to use Padlet in Ferdium and receive notifications when someone posts to one of the Padlet boards. 

I haven't been able to find a recipe for Padlet+Franz on Github. Based on the instructions, I've created a [Padlet recipe for Ferdium ](https://github.com/bfsinger/ferdiumpadlet)(hopefully I've uploaded it to Github correctly). The app seems to load correctly in Ferdium. What is not working are notifications of posts to Padlet boards. I'm not sure I have the correct code in the webview.js file. 

Also to note, my university has a special Padlet link (https://uofsussex.padlet.org/). Instead, I used https://padlet.com/ in the Github upload, to make the code more general. 

Any help is appreciated regarding the notifications; thanks!

**Comment by vraravam** [comment]
@bfsinger - please create a PR as opposed to an issue for this. Thanks!
