### ISSUE TITLE
[Recipe Request]: GCP Google Cloud

### ISSUE THREAD

**Issue by rr4444** [ferdium/ferdium-recipes#143]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Name of the service

GCP Google Cloud

### URL of the service

console.cloud.google.com

### Features you want implemented

Hi, this would be a good one to add

**Comment by vraravam** [comment]
@rr4444  - please add proper titles when creating tickets. Also, we would appreciate if the community contributes service recipes. the maintainers would not be able to create logins for each service and test all the features. Instead, we have provided a simple code generator to help you with the basics of setting up a new recipe. TIA

**Comment by rr4444** [comment]
Sorry, yes. Late night for me...

BTW I am not sure if GCP will work anyway, as things stand. Google block it with the following:

Error: 

_Couldn't sign you in
This browser or app may not be secure. [Learn more](https://support.google.com/accounts/answer/7675428?hl=en-GB)
Try using a different browser. If you’re already using a supported browser, you can try again to sign in._

I presume it's because Ferdium's browser is "embedded in a different application" (based on the link)

Can HTTP headers be set to change the declared client?

**Comment by rr4444** [comment]
Oh yes, I see that the user agent can be set. I will have to come back to this.

**Comment by cino** [comment]
Actually, closing this issue due to the "Features you want implemented" is not complete thus nobody knows what can be implemented. Feel free to-reopen and add more information.
