### ISSUE TITLE
[Bug]: Telegram do not send any sound notifications on Windows10

### ISSUE THREAD

**Issue by LennyWin10** [ferdium/ferdium-recipes#157]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Ferdium Version

6.0.0

### Recipe Name

telegram

### Recipe Version

3.3.4

### Steps to reproduce

Telegram web do not send any sound notifications in Ferdium
Do not work both for K and Z versions
Why it is not working guys?

### Expected Behavior

Need to have sound notifications

### Actual Behavior

Dont have any sound notifications

**Comment by MadelineProtoFan** [comment]
They same problem! Waiting for a fix for a long time :(

**Comment by Mark78x** [comment]
Please fit it! Very inportant thing 🙏🙏🙏🙏🙏🙏

**Comment by MadelineProtoFan** [comment]
Today after update K version started to send sound notifications! 
It was not Ferdium problem
In Z version the same problem. No sound notifications. I will use K version and no problem
PROBLEM IS SOLVED GUYS!!!!!!!

**Comment by nathanaelhoun** [comment]
As per the last comment, this issue seems solved. Please reopen it if the problem is still present :smile:
