### ISSUE TITLE
[Bug] Dark Mode is broken on Google Classroom

### ISSUE THREAD

**Issue by m1karii** [ferdium/ferdium-recipes#16]
I think the title sums it up: the Dark Mode doesn't work properly on Google Classroom

**Comment by mydarkstar** [comment]
Hi @m1karii, please use our [bug report template](https://github.com/ferdium/ferdium-recipes/issues/new?assignees=&labels=bug+%3Abeetle%3A&template=bug_report.yml&title=%5BBug%5D%3A+) when reporting bugs.
We need screenshots and the usually requested additional information to properly evaluate your issue.

I assume the custom CSS for the dark mode is outdated:
https://github.com/ferdium/ferdium-recipes/blob/main/recipes/googleclassroom/darkmode.css

If you want, you can make an attempt at fixing it via the Service Developer Tools and submitting a PR.

**Comment by mydarkstar** [comment]
Closed for inactivity and invalid reporting.
