### ISSUE TITLE
[Recipe Request]: Viber

### ISSUE THREAD

**Issue by Karam1phill** [ferdium/ferdium-recipes#169]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Name of the service

Viber

### URL of the service

viber.com

### Features you want implemented

It would be nice to have Viber.

**Comment by cino** [comment]
@Karam1phill As I understand there is only an Desktop version for Viber (https://www.viber.com/en/download/) and this is not possible to implement within Ferdium. If there is a web based version it might be possible.

For now closing this issue, feel free to re-open IF there is a web version available.
