### ISSUE TITLE
[Recipe Request]: Google Groups (groups.google.com)

### ISSUE THREAD

**Issue by Braintelligence** [ferdium/ferdium-recipes#189]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Name of the service

Google Groups

### URL of the service

https://groups.google.com

### Features you want implemented

Hello everyone,

I'd like Ferdium to support Google Groups. You can use Google Groups like a multi-user or functional mailbox and "light" issue tracker. No recipe seems to exist for Ferdium or Franz.

Implementing it in Rambox was rather easy with a custom script but Ferdium recipes look a lot more complicated.

Is anyone interested in tackling this? Together with someone experienced in making Ferdium recipes we should be able to dish out something pretty fast I think.

**Comment by vraravam** [comment]
You can folllow this guide to [create a new recipe](https://github.com/ferdium/ferdium-recipes/blob/main/docs/integration.md#create-a-recipe)

**Comment by vijay94** [comment]
Hi @vraravam can I take this up?.

**Comment by SpecialAro** [comment]
Close as per https://github.com/ferdium/ferdium-recipes/pull/207

**Comment by Braintelligence** [comment]
Thank you very much for adding the service. Is it possible to automatically stay in the group you chose within the service on reload/reopening of Ferdium?

Currently I'd like to be in two different groups at once, so I created two services. But every time I reload or restart Ferdium I need to go into the service and open up the group I want again. I'd like to "stay" in the group that I opened up this way even after reloading/restarting.

Is it possible to achieve this by editing the service?

**Comment by vraravam** [comment]
@Braintelligence - this is theoretically possible IFF the address bar url changes when you switch the chosen service. If this is the behavior, you can capture that and edit the service's `package.json` file, and set the value of the `serviceUrl` to what was shown in the address bar for that service. This process will need to be done each time there's an update to the service from a new version of Ferdium.
