### ISSUE TITLE
[Recipe Request]: Snapchat Web

### ISSUE THREAD

**Issue by Sukhacoder02** [ferdium/ferdium-recipes#190]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Name of the service

Snapchat

### URL of the service

https://web.snapchat.com

### Features you want implemented

I don't want any particular features to be implemented. Just an interface of snapchat in ferdium would be just as good.

**Comment by vraravam** [comment]
Snapchat is already present in Ferdium. please search
