### ISSUE TITLE
[Recipe Request]: Meta Business Suite

### ISSUE THREAD

**Issue by jalabaya** [ferdium/ferdium-recipes#204]
Just FYI. The link to your contributing guidelines returns 404.
https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md

Meta Business Suite
https://business.facebook.com/

I tried to add the site as a custom service. The page loads, but the overlay by Ferdi about loading the service just keeps spinning and spinning and the page is not responsive to clicks. I did look at the guide how to create a recipe, but I am not a programmer, so that is over my head.

The Meta Business suite is a platform that allows business owners to manage FB and IG messages in one place.

**Comment by vraravam** [comment]
> The link to your contributing guidelines returns 404.

@jalabaya - there are many repositories. The `CONTRIBUTING.md` is not in this repo.

> The page loads, but the overlay by Ferdi about loading....

Are you using Ferdi or Ferdium? We only support Ferdium.

I dont use FB products - so cannot comment on or implement this. Will wait for other contributors to pitch in.

**Comment by jalabaya** [comment]
Well, I had looked at other recipe requests, to see what is the preferred format here and they did reference that link.

It is Ferdium indeed.

Looking forward to see if someone can help. Thanks!

**Comment by mjeveritt** [comment]
I have the same issue as the OP:

> I tried to add the site as a custom service. The page loads, but the overlay by Ferdi about loading the service just keeps spinning and spinning and the page is not responsive to clicks.

**Comment by mjeveritt** [comment]
> I have the same issue as the OP:
> 
> I tried to add the new recipe as a new service. The page loads, but the overlay by Ferdi about loading the service just keeps spinning and spinning and the page is not responsive to clicks.

ah, deleting the Recipe, re-adding seems to make it work. There must be a glitch somewhere ...

**Comment by vraravam** [comment]
> The page loads, but the overlay by Ferdi

@mjeveritt - we do not support Ferdi. If you are using Ferdi, this is the wrong support channel.

**Comment by vraravam** [comment]
> ah, deleting the Recipe, re-adding seems to make it work. There must be a glitch somewhere ...

This most likely means that you previous installation of the service recipe was corrupt somehow.
