### ISSUE TITLE
[Recipe Request]: Jupyter Notebooks

### ISSUE THREAD

**Issue by genefyx** [ferdium/ferdium-recipes#205]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Name of the service

Jupyter Lab

### URL of the service

http://localhost:8889/lab

### Features you want implemented

# Command line option in Ferdium to run bash command  run
jupyter notebook --no-browser --NotebookApp.token=''
# Or for more security - use the command below but the token will be added ferdium
jupyter notebook --no-browser

**Comment by vraravam** [comment]
I fail to understand how this is generic/useful out side of your context?

**Comment by genefyx** [comment]
Would it be possible to add a command line option, so users can load custom web apps?

An on start and an exit option would do and allow generics?

**Comment by cino** [comment]
@genefyx Ferdium is only able to open web urls, running commands on the system is not something we can or will support.
