### ISSUE TITLE
[Recipe Request]: Whimsical.com

### ISSUE THREAD

**Issue by m0rg5** [ferdium/ferdium-recipes#206]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Name of the service

Whimsical

### URL of the service

https://whimsical.com/

### Features you want implemented

Currently I've added as custom website but it's showing address bar.

**Comment by vraravam** [comment]
Address bar can be disabled - please check the settings
<img width="643" alt="Screenshot 2022-10-17 at 8 54 55 PM" src="https://user-images.githubusercontent.com/69629/196313641-5a0cf66e-53d6-4804-8689-8c90ca9a07bb.png">
