### ISSUE TITLE
[Recipe Request]: GMX Mail

### ISSUE THREAD

**Issue by gregg00** [ferdium/ferdium-recipes#220]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Name of the service

GMX Mail

### URL of the service

https://gmx.com

### Features you want implemented

I would like to have a GMX Mail as service on ferdium

**Comment by gregg00** [comment]
Will try to create a PR https://github.com/gregg00/Ferdium-GMX-Mail

**Comment by vraravam** [comment]
@gregg00 - please raise a PR with the code in your GH repo. Once the validation checks complete, we can approve and merge it in.

**Comment by gregg00** [comment]
Will do. Thanks
