### ISSUE TITLE
[Bug]: Yahoo Mail don't load

### ISSUE THREAD

**Issue by Dominiquini** [ferdium/ferdium-recipes#223]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Ferdium Version

6.2.1-Nightly.38

### Recipe Name

Yahoo Mail

### Recipe Version

1.2.0

### Steps to reproduce

1. Start Ferdium
2. Go to Yahoo Mail recipe
3. See a blank screen without any loading indicator
4. Sometimes the recipe load, but is impossible to interact with any element of the screen!
5. Reloading the service do nothing!

### Expected Behavior

The recipe should load like all others!

### Actual Behavior

The recipe don't load; or when load, I cannot interact with the page!

### Screenshots

![Ferdium_NmjP1aa1Hc](https://user-images.githubusercontent.com/1180808/199942395-f1ba6696-0135-49c2-879c-22dcb2e28f82.png)

### Additional Information

The recipe was working fine until this week. Maybe some update this week broke this recipe...
I was always using the Nighty versions! And always update my Ferdium when a new release shows up!

**Comment by Alphrag** [comment]
@Dominiquini Hi, sorry for the lateness of this. I am currently running version `6.2.1-nightly.47` and it seems that the recipe is working. I don't have a yahoo email to test it fully, but it loads and I can interact with the page without any problem. 
Can you please confirm if this was a temporary bug/if this is now fixed thanks to changes on a version further down the line/if that is still a problem on your side? If the latter, is downgrading to a previous nightly allows you to get it back or is it not even working doing that?

**Comment by Dominiquini** [comment]
Hi. Thanks for the reply.

It's working now! It start working again some days or weeks after I opened this bug report...
I'm currently using the '6.2.1-nightly.47' version.
I'll close this issue.

Thanks.
