### ISSUE TITLE
[Recipe Request]: RocketChat

### ISSUE THREAD

**Issue by kraken-IX** [ferdium/ferdium-recipes#234]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Name of the service

Rocketchat

### URL of the service

https://de.rocket.chat/

### Features you want implemented

Dear Fredium Team,

Thank you a lot for Devolopping such an amazing alternative to Fred. 
I have a request to you.  We are using Rocketchat a lot in germany and many universities/companies have switched to it. 
Can you please add it to the services on Fredium ?

Best regards,
Kraken

**Comment by cino** [comment]
![image](https://user-images.githubusercontent.com/2735602/201369936-f853be23-c012-43cf-ab7b-a91a2041767d.png)

Hi @kraken-IX,

As visible in the screenshot above, Rocketchat already exists, are you expecting something else?

**Comment by SpecialAro** [comment]
Closing as per inactivity.
