### ISSUE TITLE
[Bug]: Mastodon doesn't load

### ISSUE THREAD

**Issue by DominusExult** [ferdium/ferdium-recipes#238]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Ferdium Version

6.2.1-nightly.46

### Recipe Name

Mastodon

### Recipe Version

1.3.0

### Steps to reproduce

1. add serive Mastodon
2. add applicable Team (in my case I added "mastodon.social"
3. enable service

### Expected Behavior

That Mastodon works

### Actual Behavior

IT gets stuck at the white screen with "Loading Mastodon"

### Additional Information

On macos 13

**Comment by Alphrag** [comment]
@DominusExult There indeed seems to have a problem with the Mastodon recipe which does not consider the "Team" value appropriately. I would suggest you to use the "Custom server" and setting it to the url of the server you use, in your case:`https://mastodon.social`. This should at least make it work for you until we get to examine how to deal with the team id appropriately.

**Comment by Alphrag** [comment]
Good! 
Yes, we noticed that these labels had disappeared (from the refactoring into ts) as we looked into a similar problem and a fix for that has come into PR https://github.com/ferdium/ferdium-app/pull/785 so they will be back soon.

**Comment by sjclark** [comment]
> @DominusExult There indeed seems to have a problem with the Mastodon recipe which does not consider the "Team" value appropriately. I would suggest you to use the "Custom server" and setting it to the url of the server you use, in your case:`https://mastodon.social`. This should at least make it work for you until we get to examine how to deal with the team id appropriately.
> 
> Let me know if this fixes the problem for you.

Yep this fixed my issue as well 👍
