### ISSUE TITLE
Contributing Guidelines and Code of Conduct are 404

### ISSUE THREAD

**Issue by DominusExult** [ferdium/ferdium-recipes#239]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Ferdium Version

6.2.1-nightly.46

### Recipe Name

BUG reporting

### Recipe Version

1.0.0

### Steps to reproduce

1. start a new issue
2. select bug report
3. click on the links for Contributing Guidelines and Code of conduct

### Expected Behavior

Being able to read either documents

### Actual Behavior

a 404 "Page not Found" Github page opens.

This is because both are linked to the branch "develop" that is no longer (if ever?) there and while code of conduct is in the main branch, the Contributing Guidelines aren't.
Or rather it should link to the code of https://github.com/ferdium/ferdium-app and not the recipes.

**Comment by Alphrag** [comment]
Well spotted thanks. It also made me realise that there are some other links/pieces of information that are no longer up to date: some were already outdated in the Ferdi repo, and we didn't check everything as it didn't seem fully necessary, but with the problem from the whatsapp recipe, it now looks quite important ^^

**Comment by DominusExult** [comment]
Well, I actually tried to read both documents instead of just clicking the checkmark 🤣
