### ISSUE TITLE
[Bug]: WhatsApp modals broken by Ferdium theme warning

### ISSUE THREAD

**Issue by grigi** [ferdium/ferdium-recipes#250]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Ferdium Version

6.2.0

### Recipe Name

WhatsApp

### Recipe Version

3.4.5

### Steps to reproduce

Right-click to delete a message.

### Expected Behavior

The modal not being modified.

### Actual Behavior

Ferdium replaces a large part (and the first button of "Delete for Me") with a warning about dark theme.

### Screenshots

![image](https://user-images.githubusercontent.com/1309160/204261184-a44ad810-f2c3-487d-b7ce-ab19ef6a8d24.png)

**Comment by SpecialAro** [comment]
This is already fixed on the latest nightlies/beta
