### ISSUE TITLE
[Bug]: Asana Browser Compatibility

### ISSUE THREAD

**Issue by isaacusmagnus** [ferdium/ferdium-recipes#259]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Ferdium Version

6.2.2

### Recipe Name

Asana

### Recipe Version

1.2.0

### Steps to reproduce

1. Go to Add a Service
2. Browse or Search for Asana
3. Log in to Asana 

Error message will display that Asana is only compatible with Edge, Chrome, Firefox, or Safari. No further interaction/use of Asana is available.

### Expected Behavior

Expecting the in-browser version of Asana to load with full feature set.

### Actual Behavior

Error message will display that Asana is only compatible with Edge, Chrome, Firefox, or Safari. No further interaction/use of Asana is available.

**Comment by SpecialAro** [comment]
Hello @isaacusmagnus , thank you for opening this issue.

Have you tried to change the user agent on the service? (Right click on the service > Edit > Scroll down to User Agent > Place your user agent, for instance: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36`)

**Comment by isaacusmagnus** [comment]
yer a wizard, @SpecialAro!
I had not fiddled with that setting (since it's right below the beta proxy settings bit) and that indeed worked. 
Thank you for catching something so direct and explaining that to me!
