### ISSUE TITLE
[Recipe Request]: (integrated) Proton Service

### ISSUE THREAD

**Issue by machiav3lli** [ferdium/ferdium-recipes#261]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Name of the service

Proton Services

### URL of the service

https://proton.me/

### Features you want implemented

This could be also interpreted as being no recipe request, rather an optimization.
The proton mail, drive, calendar recipes are limited to the respective services and as soon as one tries to open one of the other services, it jumps into the system browser with the website of the to-be-opened services.
Can we have a recipe that integrates them all in one Or rather more precisely: is there a way to open the other services within one sandbox?

Side note: enabling "open urls within ferdium" doesn't do the job.

**Comment by vraravam** [comment]
What you describe in the "Features you want implemented" section does not work for the underlying architecture of Ferdium. Others have asked for the same with Google's suite and also the MS suite.
