### ISSUE TITLE
[Recipe Request]: Viber

### ISSUE THREAD

**Issue by grgouz** [ferdium/ferdium-recipes#283]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Name of the service

Viber

### URL of the service

https://www.viber.com/

### Features you want implemented

Viber messeger

**Comment by vraravam** [comment]
```
As of today, there is no official browser version of Viber. So you have to install the app.
```
Please see https://bestim.org/viber-online.html
Closing since this is currently not possible to use viber inside Ferdium.
