### ISSUE TITLE
[Recipe Request]: LINE Request

### ISSUE THREAD

**Issue by Gr-moi** [ferdium/ferdium-recipes#294]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Name of the service

LINE Messenger

### URL of the service

https://line.me/

### Features you want implemented

Just having the messenger app would be great. Chrome has an extension for it, but I'd rather have it under Ferdium with my other apps.

**Comment by SpecialAro** [comment]
@Gr-moi I don't use this service but after reading the website you provided looks like the service doesn't have a web version. Is it true? Is it only a phone app or a chrome extension?

**Comment by Gr-moi** [comment]
Hi. Yes, there isn't a web app, just the phone app and chrome extension. However, I found this link (https://developers.line.biz/en/docs/line-login/integrate-line-login/). I'm not sure if that is of any use, my knowledge of programming is non-existent.

**Comment by SpecialAro** [comment]
Given the fact that this service doesn't have a web app (which is a requirement to integrate services on Ferdium), I'm afraid that we need to close this issue as not planned, sorry.

This integration is not possible on Ferdium until a web app (with a public access URL) is in place.

**Comment by Gr-moi** [comment]
No worries.
