### ISSUE TITLE
[Recipe Request]: Boomerang for Gmail

### ISSUE THREAD

**Issue by Falken330** [ferdium/ferdium-recipes#315]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Name of the service

boomerang

### URL of the service

https://www.boomerangapp.com/

### Features you want implemented

Boomerang is a plugin for Gmail that allows 1 click calendar scheduling.  I would like to be able to use this feature in Ferdium.

**Comment by vraravam** [comment]
Please do not create duplicates. Boomerang is a browser extension, and we don't support extensions as of this point.
