### ISSUE TITLE
[Bug]: Element - Connectivity to the server has been lost

### ISSUE THREAD

**Issue by kir0ul** [ferdium/ferdium-recipes#317]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-app/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Ferdium Version

6.2.4

### Recipe Name

Element

### Recipe Version

1.3.3

### Steps to reproduce

1. Open Ferdium
2. Log into Element

### Expected Behavior

Be able to sent and receive messages.

### Actual Behavior

Messages in Element don't get updated.

### Screenshots

![image](https://user-images.githubusercontent.com/6053592/218276140-004eacc8-daa0-4eb4-9a6f-ad6115b8deff.png)

### Additional Information

Ferdium installed with Flatpak:
- https://flathub.org/apps/details/org.ferdium.Ferdium
- https://github.com/flathub/org.ferdium.Ferdium

**Comment by vraravam** [comment]
Are other services also not able to connect? I was using element till a few days ago without any issues.

**Comment by kir0ul** [comment]
> Are other services also not able to connect? I was using element till a few days ago without any issues.

Yes, every other service work fine. Element has been broken for me for a while, but since apparently it was only for me, I deleted the service (only disabling it didn't change anything) and added it back again, now everything seems to be working! Thanks for your feedback!
