### ISSUE TITLE
[Bug]: WhatsApp always shows "Update available"

### ISSUE THREAD

**Issue by gustavotrott** [ferdium/ferdium-recipes#32]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Ferdium Version

6.0.0-nightly.33

### Recipe Name

WhatsApp

### Recipe Version

3.4.0

### Steps to reproduce

1. Configure a whatsapp service
2. Click on "Click here to update whatsapp"
3. Whatsapp will update and hide the link to update
4. Reload the Service
5. The link "Click here to update whatsapp" will be shown again

### Expected Behavior

WhatsApp should keep the updates next time I load the service.

### Actual Behavior

WhatsApp ask to update every time I load the service.

### Screenshots

![image](https://user-images.githubusercontent.com/5660191/169521824-6187a1f1-9341-44a1-968a-0cf7ae1bb4ad.png)

### Additional Information

I'm not sure if it is possible to fix!
Maybe it's just some config that I don't know how to configure properly.

Thanks a lot for the amazing work.

**Comment by vraravam** [comment]
This is not something we can control. Whatsapp seems to be testing/updating this on their server-side.

**Comment by FeikoJoosten** [comment]
I do think this is an issue on Ferdiums end. My initial guess it's most likely related to something being cached which shouldn't be cached.

I can easily reproduce the Update Available option using the following reproduction steps

1. Wait until Whatsapp has an update available
2. Click the Update Available and wait for Whatsapp to be completed
3. Reload the service and wait for Whatsapp to be reloaded
4. Notice the Update Available button is there again

You can repeat steps 2-4 at least 5 times, possibly many times more but that's when I gave up.
