### ISSUE TITLE
WhatsApp displaying message badge for messages I sent from another device

### ISSUE THREAD

**Issue by ajusidman** [ferdium/ferdium-recipes#369]
I am getting a notification and message badge on my ferdium service on my MacBook when I send a Whatsapp message to someone from another device. It's like it's treating messages I send from another device as an incoming message, which is annoying. Is there a way to set it so I only get notified when someone else sends me a message?

**Comment by thehale** [comment]
Per #321, you are more likely to get an answer to this question by posting the issue in [ferdium-app](https://github.com/ferdium/ferdium-app).

**Comment by nathanaelhoun** [comment]
Hi @ajusidman, as pointed by `@thehale`,  please open an issue in the [`ferdium-app` issue tracker](https://github.com/ferdium/ferdium-app/issues) and follow the template. 

If you followed a link to open the issue here, can you precise which one?

**Comment by mckls** [comment]
Currently in version 6.4.1  the bug is existent again.
