### ISSUE TITLE
[Bug]: Jitsi Meet stuck on "Loading"

### ISSUE THREAD

**Issue by husim0** [ferdium/ferdium-recipes#38]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Ferdium Version

6.0.0-nightly.45

### Recipe Name

Jitsi Meet

### Recipe Version

1.2.0

### Last Known working version of the recipe

Don't know

### Steps to reproduce

1. Create a service
2. Load service

### Expected Behavior

Jitsi Meet is loading correctly

### Actual Behavior

Service is stuck on "Loading Jitsi Meet"

### Screenshots

![Uploading image.png…]()

**Comment by husim0** [comment]
![image](https://user-images.githubusercontent.com/50374438/171118357-60be8e5b-fc4b-409e-8a3a-feb00d9ff043.png)

**Comment by vraravam** [comment]
This is an issue that's prevalent randomly for different services (being tracked in https://github.com/ferdium/ferdium-app/issues/157 since this is not service-specific) Please subscribe to that ticket for future updates.
