### ISSUE TITLE
[Bug]: Whatsapp, empty spaces on 2K screen

### ISSUE THREAD

**Issue by danisztls** [ferdium/ferdium-recipes#45]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Ferdium Version

6.0.0

### Recipe Name

Whatsapp

### Recipe Version

3.4.0

### Steps to reproduce

Just open service.

### Expected Behavior

Full width on 2K (2560x1440) screen.

### Actual Behavior

App max width is limited to 1600px.

### Screenshots

![Screenshot from 2022-06-06 20-29-05](https://user-images.githubusercontent.com/13279154/172268894-62d33ea4-0064-4943-9de0-e6a09aece344.png)

### Additional Information

Ferdium isn't at fault, Whatsapp non-sensical design choices are to blame. This is in the same vein of #13. Should I submit a PR?

**Comment by SpecialAro** [comment]
Hey @danisztls , I'll try to upload a PR if you think it is useful, but for the time being you can try to set this on your `user.css` file:
```
.app-wrapper-web ._1XkO3 {
    max-width: none !important;
}
```

**Comment by danisztls** [comment]
@SpecialAro thanks!
