### ISSUE TITLE
[Recipe Request]: Signal

### ISSUE THREAD

**Issue by bernikr** [ferdium/ferdium-recipes#46]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Name of the service

Signal

### Features you want implemented

I know this is not as trivial as other recipes but i think it should be possible to write a Signal integration for Ferdium since the official Signal App is an Electron App as well: https://github.com/signalapp/Signal-Desktop

If it was possible to use Signal in Ferdium I think that would be a distinguishing feature that would set it apart from similar apps.

**Comment by vraravam** [comment]
Ferdium basically renders websites / portals of services within Chromium tabs. Signal does not expose such a web page due to the encryption mechanisms they built in. Signal's developers have repeatedly refused such a thing on their roadmap.
Due to the above, it won't be possible for Ferdium to support Signal as a service.

**Comment by CC007** [comment]
Signal is open-source, right? Would it be possible to fork signal-desktop and embed that inside ferdium? From what I can see, signal is a PWA using html and typescript, so it might be possible to get that running inside a chromium tab

**Comment by victorbnl** [comment]
It is way outside of Ferdium’s scope though. If you get to fork signal-desktop and have it as web client hosted on a server of yours, in that case *maybe* we could add the recipe for your unofficial Signal client. Whilst keeping under consideration that, if it really is feasible (I don’t know how Signal works so I can’t say, but it might be impossible to connect to official Signal servers with a custom client), it would be a security hazard if not thoroughly maintained.
