### ISSUE TITLE
[Recipe Request]: Proton Drive

### ISSUE THREAD

**Issue by haykh** [ferdium/ferdium-recipes#50]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Name of the service

Proton Drive

### URL of the service

drive.proton.me

### GitHub URL to a recipe that has already been created by someone else or you

https://github.com/haykh/not-a-repository/tree/master/6-8-2022/protondrive

### Features you want implemented

So apparently Proton is undergoing a huge rebranding, and they've added Proton Calendar and Drive to their services. Proton Drive only has a web-app currently, so I think it's very much worth adding them to the services (see repo). Might also be worth changing the Proton Mail logo.

**Comment by vraravam** [comment]
@haykh - if you can specify the MIT license for that recipe, I can copy it over for use in Ferdium by all users. Sorry for the delay, somehow I didn't get notifications for this repository's tickets.

**Comment by vraravam** [comment]
Belay that, its specified as "MIT" in the `package.json` - that works for me

**Comment by vraravam** [comment]
Actually, rather than me copying each file into a recipe's PR, can you just create a PR against this repo? That way, you get attributed to the contribution!
