### ISSUE TITLE
[Recipe Request]: odysee

### ISSUE THREAD

**Issue by ghost** [ferdium/ferdium-recipes#62]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Name of the service

Odysee

### URL of the service

https://odysee.com/

### Features you want implemented

Notifcation support
Enable audio

Thats it

**Comment by hafiz-muhammad** [comment]
I've opened a pull request for Odysee recipe.

**Comment by cino** [comment]
Closing this issue as it seems to be implemented in #165 .
