### ISSUE TITLE
[Bug]: Outlook service does not properly save credentials

### ISSUE THREAD

**Issue by SpecialAro** [ferdium/ferdium-recipes#8]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Ferdium Version

6.0.0-nightly.22

### Recipe Name

Office 365 Outlook

### Recipe Version

1.6.0

### Steps to reproduce

1. Add Outlook 365 recipe
2. Login to your account
3. Close Ferdium
4. Open Ferdium
5. Login screen comes up again (shouldn't be necessary to login again)

### Expected Behavior

1. Add Outlook 365 recipe
2. Login to your account
3. Close Ferdium
4. Open Ferdium
5. Account logged in automatically

### Actual Behavior

Account is not being logged in automatically after closing and opening Ferdium.

**Comment by Sauceee** [comment]
Found a workaround: With the selfhosted option and URL: https://outlook.live.com/mail/

**Comment by SpecialAro** [comment]
> Found a workaround: With the selfhosted option and URL: https://outlook.live.com/mail/
Hello @Sauceee , yes, that's the workaround I've been using. We should migrate to that link in the future on the recipe's code.

**Comment by dchmelik** [comment]
I have same problem with some Outlook (personal, not school) but not other MS (Teams).
