### ISSUE TITLE
Bug: Can't access menus, minimise or close Window when WhatsApp service is the focus

### ISSUE THREAD

**Issue by davidrudduck** [ferdium/ferdium-recipes#83]
### Avoid duplicates

- [x] I have searched the [issues tracker](https://github.com/ferdium/ferdium-app/issues) for a bug report similar to mine, in vain

### Ferdium Version

6.0.0-nightly79

### What Operating System are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

When clicking the Menu headers, they should respond with a menu.
When clicking the Maximise, Minimise and Close buttons, they should respond as such.

### Actual Behavior

The loading status rolling line (from left to right of the top of the title bar) refreshes, but the dialogue does not respond with menu or button behaviour.
![image](https://user-images.githubusercontent.com/47308254/176065649-b6453505-33d6-40db-b8e5-bcd36413b157.png)

### Steps to reproduce

1. Open Ferdium
2. Select a WhatsApp service
3. Click into the text dialogue box of a chat
4. Click the Menu at the top of Ferdium or any of the Minimise, Maximise or Close buttons

### Screenshots

![image](https://user-images.githubusercontent.com/47308254/176065744-466e6470-8c9d-43d7-a0d8-62e419594bfd.png)

**Comment by davidrudduck** [comment]
Just reading through this other issue (https://github.com/ferdium/ferdium-app/issues/310) and when I went in and TURNED OFF the progress bar, this fixed the issue.
Might be that the issue may be more related to the Progress Bar than WhatsApp itself?

**Comment by vraravam** [comment]
That could also be the case - though the intent of the other bug was more about the service reloading every few seconds. If turning off the progress bar has fixed your issue, lets close this one please.

**Comment by davidrudduck** [comment]
Sure. Is it a concern that the new progress bar has an adverse effect on the functionality of the application? If no, then I won't bother opening a bug report for that.
