### ISSUE TITLE
[Bug]: WhatsApp lag

### ISSUE THREAD

**Issue by schwixxer** [ferdium/ferdium-recipes#84]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ferdium/ferdium-recipes/blob/develop/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ferdium/ferdium-recipes/blob/develop/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ferdium/ferdium-recipes/issues) for a feature request that matches the one I want to file, without success.

### Ferdium Version

6.0.0-nigthly.80

### Recipe Name

WhatsApp

### Recipe Version

2.2222.11

### Steps to reproduce

1. Open WhatsaApp recipe.
2. Pick any chat and type a line of Text.
3. Try scrolling through the text with your left/right key. 
4. Lag happens every few seconds. 

### Expected Behavior

No loaging while normal usage

### Actual Behavior

WhatsApp is laging if you try to do anything active within the app, especially if you try to scroll through text or switch chats.
The whole recipe is freezing for a few seconds. Ferdium itself and other recipes work fine while WA is frozen.
Happend also with Ferdi. Does not happen in WhatsappWeb (2.2222.11) in Chrome (102.0.5005.115)

This only happens with WhatsApp not with any other messenger/Ferdium application.

While laging CPU usage of WhatsApp Tab goes up to 30%.

Dev Console outputs following Error:

```
Throttling navigation to prevent the browser from hanging. See https://crbug.com/1038223. Command line switch --disable-ipc-flooding-protection can be used to bypass the protection
bootstrap_main.c7fae15c2be134004f59.js:13
```

### Screenshots

https://youtu.be/gZ9krkI-LOc

**Comment by SpecialAro** [comment]
This should be fixed in the latest nightly. Please update!
